const rooms = [
  {
    id: 1,
    floor_number: 1,
    room_number: 101,
    room_type: "Deluxe Room",
    price_per_night: 33,
    currency: "USD",
    capacity: 2,
    beds: 1,
    status: "available",
    view: "city",
    description: "Comfortable deluxe room with modern interior and city view.",
    amenities: {
      wifi: true,
      swimming_pool: true,
      air_conditioning: true,
      tv: true,
      minibar: false,
    },
  },
  {
    id: 2,
    floor_number: 1,
    room_number: 102,
    room_type: "Standard Room",
    price_per_night: 25,
    currency: "USD",
    capacity: 2,
    beds: 1,
    status: "booked",
    view: "garden",
    description: "Cozy standard room perfect for short stays.",
    amenities: {
      wifi: true,
      swimming_pool: false,
      air_conditioning: true,
      tv: true,
      minibar: false,
    },
  },
  {
    id: 3,
    floor_number: 2,
    room_number: 201,
    room_type: "Executive Room",
    price_per_night: 45,
    currency: "USD",
    capacity: 3,
    beds: 2,
    status: "available",
    view: "city",
    description: "Spacious executive room with premium comfort.",
    amenities: {
      wifi: true,
      swimming_pool: true,
      air_conditioning: true,
      tv: true,
      minibar: true,
    },
  },
  {
    id: 4,
    floor_number: 2,
    room_number: 202,
    room_type: "Family Room",
    price_per_night: 60,
    currency: "USD",
    capacity: 4,
    beds: 3,
    status: "maintenance",
    view: "garden",
    description: "Large family room suitable for group stays.",
    amenities: {
      wifi: true,
      swimming_pool: true,
      air_conditioning: true,
      tv: true,
      minibar: true,
    },
  },
  {
    id: 5,
    floor_number: 3,
    room_number: 301,
    room_type: "Presidential Suite",
    price_per_night: 120,
    currency: "USD",
    capacity: 5,
    beds: 3,
    status: "available",
    view: "city skyline",
    description: "Luxury suite with premium services and panoramic view.",
    amenities: {
      wifi: true,
      swimming_pool: true,
      air_conditioning: true,
      tv: true,
      minibar: true,
      jacuzzi: true,
    },
  },
];

export default rooms;