const rooms = [
  {
    id: 1,
    floor_number: 1,
    room_number: 101,
    room_type: "Deluxe Room",
    price_per_night: 33,
    currency: "USD",
    capacity: 2,
    beds: 1,
    status: "available",
    view: "city",
    description: "Comfortable deluxe room with modern interior and city view.",
    amenities: {
      "WI-Fi": true,
      "Swimming Pool": true,
      "Air Conditioning": true,
      "TV": true,
      "Minibar": false,
    },
    images: {},
  },
  {
    id: 2,
    floor_number: 1,
    room_number: 102,
    room_type: "Standard Room",
    price_per_night: 25,
    currency: "USD",
    capacity: 2,
    beds: 1,
    status: "booked",
    view: "garden",
    description: "Cozy standard room perfect for short stays.",
    amenities: {
      "WI-Fi": true,
      "Swimming Pool": false,
      "Air Conditioning": true,
      "TV": true,
      "Minibar": false,
    },
    images: {},
  },
  {
    id: 3,
    floor_number: 2,
    room_number: 201,
    room_type: "Executive Room",
    price_per_night: 45,
    currency: "USD",
    capacity: 3,
    beds: 2,
    status: "available",
    view: "city",
    description: "Spacious executive room with premium comfort.",
    amenities: {
      "WI-Fi": true,
      "Swimming Pool": true,
      "Air Conditioning": true,
      "TV": true,
      "Minibar": true,
    },
    images: {},
  },
  {
    id: 4,
    floor_number: 2,
    room_number: 202,
    room_type: "Family Room",
    price_per_night: 60,
    currency: "USD",
    capacity: 4,
    beds: 3,
    status: "maintenance",
    view: "garden",
    description: "Large family room suitable for group stays.",
    amenities: {
      "WI-Fi": false,
      "Swimming Pool": true,
      "Air Conditioning": true,
      "TV": true,
      "Minibar": true,
    },
    images: {},
  },
  {
    id: 5,
    floor_number: 3,
    room_number: 301,
    room_type: "Presidential Suite",
    price_per_night: 120,
    currency: "USD",
    capacity: 5,
    beds: 3,
    status: "available",
    view: "city skyline",
    description: "Luxury suite with premium services and panoramic view.",
    amenities: {
     "WI-Fi": true,
      "Swimming Pool": false,
      "Air Conditioning": true,
      "TV": false,
      "Minibar": false,
    },
    images: {},
  },
   {
    id: 6,
    floor_number: 3,
    room_number: 302,
    room_type: "Superior Room",
    price_per_night: 55,
    currency: "USD",
    capacity: 3,
    beds: 2,
    status: "booked",
    view: "city",
    description: "Elegant superior room with modern amenities.",
    amenities: {
      "Wi-Fi": true,
      "Swimming Pool": true,
      "Air Conditioning": true,
      "TV": true,
      "Minibar": true,
      "Parking": true,
      "Gym": true,
      "Breakfast Included": true,
    },
    images: {},
  },
  {
    id: 7,
    floor_number: 4,
    room_number: 401,
    room_type: "Single Room",
    price_per_night: 20,
    currency: "USD",
    capacity: 1,
    beds: 1,
    status: "available",
    view: "garden",
    description: "Compact single room for solo travelers.",
    amenities: {
      "Wi-Fi": true,
      "Swimming Pool": false,
      "Air Conditioning": true,
      "TV": false,
      "Minibar": false,
      "Parking": true,
      "Gym": false,
      "Breakfast Included": false,
    },
    images: {},
  },
  {
    id: 8,
    floor_number: 4,
    room_number: 402,
    room_type: "Double Room",
    price_per_night: 35,
    currency: "USD",
    capacity: 2,
    beds: 1,
    status: "available",
    view: "city",
    description: "Comfortable double room with balcony.",
    amenities: {
      "Wi-Fi": true,
      "Swimming Pool": true,
      "Air Conditioning": true,
      "TV": true,
      "Minibar": false,
      "Parking": true,
      "Gym": true,
      "Breakfast Included": true,
    },
    images: {},
  },
  {
    id: 9,
    floor_number: 5,
    room_number: 501,
    room_type: "Luxury Suite",
    price_per_night: 150,
    currency: "USD",
    capacity: 4,
    beds: 2,
    status: "booked",
    view: "city skyline",
    description: "High-end luxury suite with exclusive services.",
    amenities: {
      "Wi-Fi": true,
      "Swimming Pool": true,
      "Air Conditioning": true,
      "TV": true,
      "Minibar": true,
      "Parking": true,
      "Gym": true,
      "Breakfast Included": true,
      "Jacuzzi": true,
      "Private Balcony": true,
    },
    images: {},
  },
  {
    id: 10,
    floor_number: 5,
    room_number: 502,
    room_type: "Economy Room",
    price_per_night: 18,
    currency: "USD",
    capacity: 2,
    beds: 1,
    status: "maintenance",
    view: "street",
    description: "Affordable room for budget travelers.",
    amenities: {
      "Wi-Fi": true,
      "Swimming Pool": false,
      "Air Conditioning": false,
      "TV": true,
      "Minibar": false,
      "Parking": false,
      "Gym": false,
      "Breakfast Included": false,
    },
    images: {},
  },
   {
    id: 11,
    floor_number: 6,
    room_number: 601,
    room_type: "Business Suite",
    price_per_night: 85,
    currency: "USD",
    capacity: 2,
    beds: 1,
    status: "available",
    view: "city",
    description: "Designed for business travelers with workspace and comfort.",
    amenities: {
      "Wi-Fi": true,
      "Swimming Pool": true,
      "Air Conditioning": true,
      "TV": true,
      "Minibar": true,
      "Parking": true,
      "Gym": true,
      "Breakfast Included": true,
      "Workspace": true,
      "Conference Access": true,
    },
    images: {},
  },
  {
    id: 12,
    floor_number: 6,
    room_number: 602,
    room_type: "Twin Room",
    price_per_night: 40,
    currency: "USD",
    capacity: 2,
    beds: 2,
    status: "booked",
    view: "garden",
    description: "Comfortable twin room ideal for friends or colleagues.",
    amenities: {
      "Wi-Fi": true,
      "Swimming Pool": false,
      "Air Conditioning": true,
      "TV": true,
      "Minibar": false,
      "Parking": true,
      "Gym": false,
      "Breakfast Included": true,
      "Laundry Service": true,
    },
    images: {},
  },
  {
    id: 13,
    floor_number: 7,
    room_number: 701,
    room_type: "Honeymoon Suite",
    price_per_night: 180,
    currency: "USD",
    capacity: 2,
    beds: 1,
    status: "available",
    view: "city skyline",
    description: "Romantic suite with luxury setup for couples.",
    amenities: {
      "Wi-Fi": true,
      "Swimming Pool": true,
      "Air Conditioning": true,
      "TV": true,
      "Minibar": true,
      "Parking": true,
      "Gym": true,
      "Breakfast Included": true,
      "Jacuzzi": true,
      "Private Balcony": true,
      "Room Service": true,
      "Smart Lighting": true,
    },
    images: {},
  },
];

export default rooms;